In [1]:


import numpy as np 
import pandas as pd 


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub

/kaggle/input/datasets/dhoogla/csecicids2018/DoS2-Friday-16-02-2018_TrafficForML_CICFlowMeter.parquet
/kaggle/input/datasets/dhoogla/csecicids2018/DoS1-Thursday-15-02-2018_TrafficForML_CICFlowMeter.parquet
/kaggle/input/datasets/dhoogla/csecicids2018/DDoS1-Tuesday-20-02-2018_TrafficForML_CICFlowMeter.parquet
/kaggle/input/datasets/dhoogla/csecicids2018/Web2-Friday-23-02-2018_TrafficForML_CICFlowMeter.parquet
/kaggle/input/datasets/dhoogla/csecicids2018/Web1-Thursday-22-02-2018_TrafficForML_CICFlowMeter.parquet
/kaggle/input/datasets/dhoogla/csecicids2018/Botnet-Friday-02-03-2018_TrafficForML_CICFlowMeter.parquet
/kaggle/input/datasets/dhoogla/csecicids2018/Infil2-Thursday-01-03-2018_TrafficForML_CICFlowMeter.parquet
/kaggle/input/datasets/dhoogla/csecicids2018/DDoS2-Wednesday-21-02-2018_TrafficForML_CICFlowMeter.parquet
/kaggle/input/datasets/dhoogla/csecicids2018/Infil1-Wednesday-28-02-2018_TrafficForML_CICFlowMeter.parquet
/kaggle/input/datasets/dhoogla/csecicids2018/Bruteforce-Wednesday-14-02-2018_TrafficForML_CICFlowMeter.parquet

In [2]:
import glob

files = glob.glob("/kaggle/input/datasets/dhoogla/csecicids2018/*.parquet")

print("Total files:", len(files))
print(files)

Total files: 10
['/kaggle/input/datasets/dhoogla/csecicids2018/DoS2-Friday-16-02-2018_TrafficForML_CICFlowMeter.parquet', '/kaggle/input/datasets/dhoogla/csecicids2018/DoS1-Thursday-15-02-2018_TrafficForML_CICFlowMeter.parquet', '/kaggle/input/datasets/dhoogla/csecicids2018/DDoS1-Tuesday-20-02-2018_TrafficForML_CICFlowMeter.parquet', '/kaggle/input/datasets/dhoogla/csecicids2018/Web2-Friday-23-02-2018_TrafficForML_CICFlowMeter.parquet', '/kaggle/input/datasets/dhoogla/csecicids2018/Web1-Thursday-22-02-2018_TrafficForML_CICFlowMeter.parquet', '/kaggle/input/datasets/dhoogla/csecicids2018/Botnet-Friday-02-03-2018_TrafficForML_CICFlowMeter.parquet', '/kaggle/input/datasets/dhoogla/csecicids2018/Infil2-Thursday-01-03-2018_TrafficForML_CICFlowMeter.parquet', '/kaggle/input/datasets/dhoogla/csecicids2018/DDoS2-Wednesday-21-02-2018_TrafficForML_CICFlowMeter.parquet', '/kaggle/input/datasets/dhoogla/csecicids2018/Infil1-Wednesday-28-02-2018_TrafficForML_CICFlowMeter.parquet', '/kaggle/input/datasets/dhoogla/csecicids2018/Bruteforce-Wednesday-14-02-2018_TrafficForML_CICFlowMeter.parquet']

In [3]:
import pandas as pd

df = pd.read_parquet(files[0])

print(df.shape)
df.head()

(591873, 78)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,112640768,3,0,0,0,0,0,0.00000,0.000000,...,0,0.0,0.0,0,0,56300000.0,138.592926,56300000,56300000,Benign
1,0,112641773,3,0,0,0,0,0,0.00000,0.000000,...,0,0.0,0.0,0,0,56300000.0,263.750824,56300000,56300000,Benign
2,6,20784143,23,44,2416,1344,240,64,105.04348,54.542294,...,20,2624734.0,0.0,2624734,2624734,9058214.0,0.000000,9058214,9058214,Benign
3,0,112640836,3,0,0,0,0,0,0.00000,0.000000,...,0,0.0,0.0,0,0,56300000.0,82.024384,56300000,56300000,Benign
4,6,20,1,1,0,0,0,0,0.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign

In [4]:
print(df.count())
print(len(df.columns))

Protocol                    591873
Flow Duration               591873
Total Fwd Packets           591873
Total Backward Packets      591873
Fwd Packets Length Total    591873
                             ...
Idle Mean                   591873
Idle Std                    591873
Idle Max                    591873
Idle Min                    591873
Label                       591873
Length: 78, dtype: int64
78

In [5]:
import pandas as pd

dfs = []

for file in files:
  
    print("Reading:", file)

    temp = pd.read_parquet(file)

    print("Shape:", temp.shape)

    dfs.append(temp)

Reading: /kaggle/input/datasets/dhoogla/csecicids2018/DoS2-Friday-16-02-2018_TrafficForML_CICFlowMeter.parquet
Shape: (591873, 78)
Reading: /kaggle/input/datasets/dhoogla/csecicids2018/DoS1-Thursday-15-02-2018_TrafficForML_CICFlowMeter.parquet
Shape: (794812, 78)
Reading: /kaggle/input/datasets/dhoogla/csecicids2018/DDoS1-Tuesday-20-02-2018_TrafficForML_CICFlowMeter.parquet
Shape: (954846, 78)
Reading: /kaggle/input/datasets/dhoogla/csecicids2018/Web2-Friday-23-02-2018_TrafficForML_CICFlowMeter.parquet
Shape: (829405, 78)
Reading: /kaggle/input/datasets/dhoogla/csecicids2018/Web1-Thursday-22-02-2018_TrafficForML_CICFlowMeter.parquet
Shape: (830224, 78)
Reading: /kaggle/input/datasets/dhoogla/csecicids2018/Botnet-Friday-02-03-2018_TrafficForML_CICFlowMeter.parquet
Shape: (771587, 78)
Reading: /kaggle/input/datasets/dhoogla/csecicids2018/Infil2-Thursday-01-03-2018_TrafficForML_CICFlowMeter.parquet
Shape: (249170, 78)
Reading: /kaggle/input/datasets/dhoogla/csecicids2018/DDoS2-Wednesday-21-02-2018_TrafficForML_CICFlowMeter.parquet
Shape: (561396, 78)
Reading: /kaggle/input/datasets/dhoogla/csecicids2018/Infil1-Wednesday-28-02-2018_TrafficForML_CICFlowMeter.parquet
Shape: (456873, 78)
Reading: /kaggle/input/datasets/dhoogla/csecicids2018/Bruteforce-Wednesday-14-02-2018_TrafficForML_CICFlowMeter.parquet
Shape: (619346, 78)

In [6]:
df = pd.concat(dfs, ignore_index=True)

print(df.shape)

(6659532, 78)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6659532 entries, 0 to 6659531
Data columns (total 78 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Protocol                  int8
 1   Flow Duration             int64
 2   Total Fwd Packets         int32
 3   Total Backward Packets    int32
 4   Fwd Packets Length Total  int32
 5   Bwd Packets Length Total  float64
 6   Fwd Packet Length Max     int32
 7   Fwd Packet Length Min     int16
 8   Fwd Packet Length Mean    float32
 9   Fwd Packet Length Std     float32
 10  Bwd Packet Length Max     int32
 11  Bwd Packet Length Min     int16
 12  Bwd Packet Length Mean    float32
 13  Bwd Packet Length Std     float32
 14  Flow Bytes/s              float64
 15  Flow Packets/s            float64
 16  Flow IAT Mean             float32
 17  Flow IAT Std              float32
 18  Flow IAT Max              float64
 19  Flow IAT Min              float64
 20  Fwd IAT Total             float64
 21  Fwd IAT Mean              float32
 22  Fwd IAT Std               float32
 23  Fwd IAT Max               float64
 24  Fwd IAT Min               float64
 25  Bwd IAT Total             float64
 26  Bwd IAT Mean              float32
 27  Bwd IAT Std               float32
 28  Bwd IAT Max               float64
 29  Bwd IAT Min               float64
 30  Fwd PSH Flags             int8
 31  Bwd PSH Flags             int8
 32  Fwd URG Flags             int8
 33  Bwd URG Flags             int8
 34  Fwd Header Length         int32
 35  Bwd Header Length         int32
 36  Fwd Packets/s             float32
 37  Bwd Packets/s             float32
 38  Packet Length Min         int16
 39  Packet Length Max         int32
 40  Packet Length Mean        float32
 41  Packet Length Std         float32
 42  Packet Length Variance    float32
 43  FIN Flag Count            int8
 44  SYN Flag Count            int8
 45  RST Flag Count            int8
 46  PSH Flag Count            int8
 47  ACK Flag Count            int8
 48  URG Flag Count            int8
 49  CWE Flag Count            int8
 50  ECE Flag Count            int8
 51  Down/Up Ratio             int16
 52  Avg Packet Size           float32
 53  Avg Fwd Segment Size      float32
 54  Avg Bwd Segment Size      float32
 55  Fwd Avg Bytes/Bulk        int8
 56  Fwd Avg Packets/Bulk      int8
 57  Fwd Avg Bulk Rate         int8
 58  Bwd Avg Bytes/Bulk        int8
 59  Bwd Avg Packets/Bulk      int8
 60  Bwd Avg Bulk Rate         int8
 61  Subflow Fwd Packets       int32
 62  Subflow Fwd Bytes         int32
 63  Subflow Bwd Packets       int32
 64  Subflow Bwd Bytes         int32
 65  Init Fwd Win Bytes        int32
 66  Init Bwd Win Bytes        int32
 67  Fwd Act Data Packets      int32
 68  Fwd Seg Size Min          int8
 69  Active Mean               float32
 70  Active Std                float32
 71  Active Max                float64
 72  Active Min                float64
 73  Idle Mean                 float32
 74  Idle Std                  float32
 75  Idle Max                  float64
 76  Idle Min                  float64
 77  Label                     object
dtypes: float32(22), float64(15), int16(4), int32(15), int64(1), int8(20), object(1)
memory usage: 1.9+ GB

In [8]:
import pandas as pd

df.describe()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,...,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06,6.659532e+06
mean,8.162630e+00,1.460836e+07,5.051647e+01,8.055791e+00,1.973359e+03,6.222823e+03,2.958276e+02,9.036304e+00,6.859881e+01,1.125543e+02,...,4.628435e+01,1.865925e+01,1.171216e+05,5.475629e+04,1.871040e+05,8.270550e+04,7.218752e+06,4.952411e+05,8.054734e+06,6.600027e+06
std,4.544056e+00,7.704883e+08,2.373863e+03,1.975216e+02,9.702574e+04,2.806028e+05,3.561090e+02,2.501043e+01,7.132287e+01,1.465933e+02,...,2.372740e+03,7.141310e+00,1.653610e+06,9.566876e+05,2.196363e+06,1.422508e+06,4.105831e+08,2.641382e+08,9.762279e+08,9.809106e+07
min,0.000000e+00,-9.190110e+11,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.000000e+00,8.064000e+03,2.000000e+00,1.000000e+00,2.000000e+01,0.000000e+00,2.000000e+01,0.000000e+00,6.666667e+00,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.000000e+00,6.955760e+05,3.000000e+00,2.000000e+00,9.700000e+01,2.520000e+02,8.200000e+01,0.000000e+00,4.500000e+01,3.059956e+01,...,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,6.000000e+00,5.150532e+06,7.000000e+00,5.000000e+00,9.350000e+02,9.640000e+02,6.610000e+02,0.000000e+00,1.086667e+02,1.965220e+02,...,3.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,1.700000e+01,1.200000e+08,3.096290e+05,1.231180e+05,1.443918e+08,1.563604e+08,6.444000e+04,1.460000e+03,1.652931e+04,1.840158e+04,...,3.096280e+05,5.600000e+01,1.140000e+08,7.495335e+07,1.140000e+08,1.140000e+08,3.955714e+11,2.622479e+11,9.797810e+11,2.399340e+11

In [9]:
df.isnull().sum()

Protocol                    0
Flow Duration               0
Total Fwd Packets           0
Total Backward Packets      0
Fwd Packets Length Total    0
                           ..
Idle Mean                   0
Idle Std                    0
Idle Max                    0
Idle Min                    0
Label                       0
Length: 78, dtype: int64

In [10]:
print("Duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates()

Duplicate rows: 339529

In [11]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [12]:
df.describe()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,...,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06,6.320003e+06
mean,7.883304e+00,1.534224e+07,5.315937e+01,8.446309e+00,2.077495e+03,6.553642e+03,3.099673e+02,7.985031e+00,7.063628e+01,1.184832e+02,...,4.876549e+01,1.902539e+01,1.234137e+05,5.769797e+04,1.971558e+05,8.714868e+04,7.585880e+06,5.218465e+05,8.466775e+06,6.933918e+06
std,4.331276e+00,7.909047e+08,2.436766e+03,2.027505e+02,9.959683e+04,2.880379e+05,3.600947e+02,2.445188e+01,7.213158e+01,1.481875e+02,...,2.435617e+03,7.025591e+00,1.697095e+06,9.819161e+05,2.254150e+06,1.460086e+06,4.214676e+08,2.711405e+08,1.002105e+09,1.006734e+08
min,0.000000e+00,-9.190110e+11,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.000000e+00,1.262800e+04,2.000000e+00,1.000000e+00,2.000000e+01,0.000000e+00,2.000000e+01,0.000000e+00,6.666667e+00,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.000000e+00,1.118989e+06,3.000000e+00,3.000000e+00,1.520000e+02,2.910000e+02,1.030000e+02,0.000000e+00,4.800000e+01,4.850000e+01,...,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,6.000000e+00,5.422096e+06,8.000000e+00,6.000000e+00,9.350000e+02,9.640000e+02,6.610000e+02,0.000000e+00,1.130000e+02,2.022945e+02,...,4.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,1.700000e+01,1.200000e+08,3.096290e+05,1.231180e+05,1.443918e+08,1.563604e+08,6.444000e+04,1.460000e+03,1.652931e+04,1.840158e+04,...,3.096280e+05,5.600000e+01,1.140000e+08,7.495335e+07,1.140000e+08,1.140000e+08,3.955714e+11,2.622479e+11,9.797810e+11,2.399340e+11

In [13]:
df = df[df["Flow Duration"] >= 0]

In [14]:
df.describe()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,6.319989e+06,6.319989e+06,6.319989e+06,6.319989e+06,6.319989e+06,6.319989e+06,6.319989e+06,6.319989e+06,6.319989e+06,6.319989e+06,...,6.319989e+06,6.319989e+06,6.319989e+06,6.319989e+06,6.319989e+06,6.319989e+06,6319989.0,6.319989e+06,6.319989e+06,6.319989e+06
mean,7.883321e+00,1.630678e+07,5.315928e+01,8.446328e+00,2.077499e+03,6.553657e+03,3.099680e+02,7.985049e+00,7.063649e+01,1.184835e+02,...,4.876560e+01,1.902543e+01,1.234140e+05,5.769811e+04,1.971562e+05,8.714888e+04,7039246.5,1.747588e+05,7.196464e+06,6.872532e+06
std,4.331265e+00,3.368373e+07,2.436769e+03,2.027507e+02,9.959694e+04,2.880382e+05,3.600948e+02,2.445190e+01,7.213160e+01,1.481876e+02,...,2.435620e+03,7.025542e+00,1.697096e+06,9.819172e+05,2.254152e+06,1.460088e+06,18787664.0,1.821381e+06,1.953899e+07,1.920361e+07
min,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.000000e+00,1.262800e+04,2.000000e+00,1.000000e+00,2.000000e+01,0.000000e+00,2.000000e+01,0.000000e+00,6.666667e+00,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.000000e+00,1.119001e+06,3.000000e+00,3.000000e+00,1.520000e+02,2.910000e+02,1.030000e+02,0.000000e+00,4.800000e+01,4.850000e+01,...,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
75%,6.000000e+00,5.422102e+06,8.000000e+00,6.000000e+00,9.350000e+02,9.640000e+02,6.610000e+02,0.000000e+00,1.130000e+02,2.022945e+02,...,4.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
max,1.700000e+01,1.200000e+08,3.096290e+05,1.231180e+05,1.443918e+08,1.563604e+08,6.444000e+04,1.460000e+03,1.652931e+04,1.840158e+04,...,3.096280e+05,5.600000e+01,1.140000e+08,7.495335e+07,1.140000e+08,1.140000e+08,120000000.0,7.590000e+07,1.200000e+08,1.200000e+08

In [15]:
df["Label"].value_counts()

Label
Benign                      4994146
DDoS attacks-LOIC-HTTP       575364
DDOS attack-HOIC             198861
DoS attacks-Hulk             145199
Bot                          144535
Infilteration                113819
SSH-Bruteforce                94048
DoS attacks-GoldenEye         41406
DoS attacks-Slowloris          9908
DDOS attack-LOIC-UDP           1730
Brute Force -Web                553
Brute Force -XSS                228
SQL Injection                    84
DoS attacks-SlowHTTPTest         55
FTP-BruteForce                   53
Name: count, dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Label"] = le.fit_transform(df["Label"])

In [17]:
print(df["Label"].unique())
print(df["Label"].value_counts())

[ 0  9  8  7 10  6  2  3 13  1 12  5  4 11 14]
Label
0     4994146
6      575364
4      198861
8      145199
1      144535
12     113819
14      94048
7       41406
10       9908
5        1730
2         553
3         228
13         84
9          55
11         53
Name: count, dtype: int64

In [18]:
X = df.drop("Label", axis=1)
y = df["Label"]

In [19]:
print(X.shape)
print(y.shape)

(6319989, 77)
(6319989,)

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [21]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5055991, 77)
(1263998, 77)
(5055991,)
(1263998,)

In [22]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
df_before = df.copy()

In [24]:
print(df_before["Label"].value_counts())
print(df["Label"].value_counts())

Label
0     4994146
6      575364
4      198861
8      145199
1      144535
12     113819
14      94048
7       41406
10       9908
5        1730
2         553
3         228
13         84
9          55
11         53
Name: count, dtype: int64
Label
0     4994146
6      575364
4      198861
8      145199
1      144535
12     113819
14      94048
7       41406
10       9908
5        1730
2         553
3         228
13         84
9          55
11         53
Name: count, dtype: int64

In [25]:
print(df.shape)
df.info()

(6319989, 78)
<class 'pandas.core.frame.DataFrame'>
Index: 6319989 entries, 0 to 6659531
Data columns (total 78 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Protocol                  int8
 1   Flow Duration             int64
 2   Total Fwd Packets         int32
 3   Total Backward Packets    int32
 4   Fwd Packets Length Total  int32
 5   Bwd Packets Length Total  float64
 6   Fwd Packet Length Max     int32
 7   Fwd Packet Length Min     int16
 8   Fwd Packet Length Mean    float32
 9   Fwd Packet Length Std     float32
 10  Bwd Packet Length Max     int32
 11  Bwd Packet Length Min     int16
 12  Bwd Packet Length Mean    float32
 13  Bwd Packet Length Std     float32
 14  Flow Bytes/s              float64
 15  Flow Packets/s            float64
 16  Flow IAT Mean             float32
 17  Flow IAT Std              float32
 18  Flow IAT Max              float64
 19  Flow IAT Min              float64
 20  Fwd IAT Total             float64
 21  Fwd IAT Mean              float32
 22  Fwd IAT Std               float32
 23  Fwd IAT Max               float64
 24  Fwd IAT Min               float64
 25  Bwd IAT Total             float64
 26  Bwd IAT Mean              float32
 27  Bwd IAT Std               float32
 28  Bwd IAT Max               float64
 29  Bwd IAT Min               float64
 30  Fwd PSH Flags             int8
 31  Bwd PSH Flags             int8
 32  Fwd URG Flags             int8
 33  Bwd URG Flags             int8
 34  Fwd Header Length         int32
 35  Bwd Header Length         int32
 36  Fwd Packets/s             float32
 37  Bwd Packets/s             float32
 38  Packet Length Min         int16
 39  Packet Length Max         int32
 40  Packet Length Mean        float32
 41  Packet Length Std         float32
 42  Packet Length Variance    float32
 43  FIN Flag Count            int8
 44  SYN Flag Count            int8
 45  RST Flag Count            int8
 46  PSH Flag Count            int8
 47  ACK Flag Count            int8
 48  URG Flag Count            int8
 49  CWE Flag Count            int8
 50  ECE Flag Count            int8
 51  Down/Up Ratio             int16
 52  Avg Packet Size           float32
 53  Avg Fwd Segment Size      float32
 54  Avg Bwd Segment Size      float32
 55  Fwd Avg Bytes/Bulk        int8
 56  Fwd Avg Packets/Bulk      int8
 57  Fwd Avg Bulk Rate         int8
 58  Bwd Avg Bytes/Bulk        int8
 59  Bwd Avg Packets/Bulk      int8
 60  Bwd Avg Bulk Rate         int8
 61  Subflow Fwd Packets       int32
 62  Subflow Fwd Bytes         int32
 63  Subflow Bwd Packets       int32
 64  Subflow Bwd Bytes         int32
 65  Init Fwd Win Bytes        int32
 66  Init Bwd Win Bytes        int32
 67  Fwd Act Data Packets      int32
 68  Fwd Seg Size Min          int8
 69  Active Mean               float32
 70  Active Std                float32
 71  Active Max                float64
 72  Active Min                float64
 73  Idle Mean                 float32
 74  Idle Std                  float32
 75  Idle Max                  float64
 76  Idle Min                  float64
 77  Label                     int64
dtypes: float32(22), float64(15), int16(4), int32(15), int64(2), int8(20)
memory usage: 1.9 GB

In [26]:
import os
import joblib

os.makedirs("outputs/splits", exist_ok=True)
os.makedirs("outputs/models", exist_ok=True)

joblib.dump(
    (X_train, X_test, y_train, y_test),
    "outputs/splits/train_test.pkl"
)

joblib.dump(
    le,
    "outputs/models/label_encoder.pkl"
)

print("Saved Successfully")

Saved Successfully

In [27]:
import os

for root, dirs, files in os.walk("outputs"):
    for file in files:
        print(os.path.join(root, file))

outputs/models/label_encoder.pkl
outputs/splits/train_test.pkl

In [28]:
import joblib

joblib.dump(
    scaler,
    "outputs/models/minmax_scaler.pkl"
)

print("MinMaxScaler saved successfully!")

MinMaxScaler saved successfully!

In [29]:
import os

for root, dirs, files in os.walk("outputs"):
    for file in files:
        print(os.path.join(root, file))

outputs/models/minmax_scaler.pkl
outputs/models/label_encoder.pkl
outputs/splits/train_test.pkl