In [2]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


import kagglehub

/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/__results__.html
/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/__notebook__.ipynb
/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/__output__.json
/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/custom.css
/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/outputs/results/Xgboost_metrics.csv
/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/outputs/results/xgb_confusion_matrix.png
/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/outputs/results/xgb_classification_report.csv
/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/outputs/models/XGboost.pkl
/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/__results___files/__results___15_0.png
/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/__results___files/__results___10_0.png
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/__results__.html
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/__notebook__.ipynb
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/__output__.json
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/custom.css
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/outputs/results/catb_classification_report.csv
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/outputs/results/catb_confusion_matrix.png
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/outputs/results/catb_metrics.csv
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/outputs/models/catboost.pkl
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/__results___files/__results___8_0.png
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/__results___files/__results___13_0.png
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/catboost_info/learn_error.tsv
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/catboost_info/catboost_training.json
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/catboost_info/time_left.tsv
/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/catboost_info/learn/events.out.tfevents
/kaggle/input/notebooks/hafsaferdousi5/2-2model-catboost/__results__.html
/kaggle/input/notebooks/hafsaferdousi5/2-2model-catboost/__notebook__.ipynb
/kaggle/input/notebooks/hafsaferdousi5/2-2model-catboost/__output__.json
/kaggle/input/notebooks/hafsaferdousi5/2-2model-catboost/custom.css
/kaggle/input/notebooks/hafsaferdousi5/3-feature-selection/__results__.html
/kaggle/input/notebooks/hafsaferdousi5/3-feature-selection/__notebook__.ipynb
/kaggle/input/notebooks/hafsaferdousi5/3-feature-selection/__output__.json
/kaggle/input/notebooks/hafsaferdousi5/3-feature-selection/custom.css
/kaggle/input/notebooks/hafsaferdousi5/3-feature-selection/outputs/features/feature_names.csv
/kaggle/input/notebooks/hafsaferdousi5/3-feature-selection/outputs/features/feature_names.pkl
/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/__results__.html
/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/__notebook__.ipynb
/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/__output__.json
/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/custom.css
/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/outputs/results/rf_metrics.csv
/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/outputs/results/rf_confusion_matrix.png
/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/outputs/results/rf_classification_report.csv
/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/outputs/models/random_forest.pkl
/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/__results___files/__results___11_0.png
/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/__results___files/__results___16_0.png
/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/__results__.html
/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/__notebook__.ipynb
/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/__output__.json
/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/custom.css
/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/splits/train_test.pkl
/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/label_encoder.pkl
/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/minmax_scaler.pkl
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/__results__.html
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/__notebook__.ipynb
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/__output__.json
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/custom.css
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/outputs/results/lightgbm_leaves31_metrics.csv
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/outputs/results/lightgbm_leaves31_classification_report.csv
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/outputs/results/lightgbm_leaves31_confusion_matrix.png
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/outputs/models/lightgbm_leaves31.pkl
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/__results___files/__results___15_0.png
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/__results___files/__results___20_0.png
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/__results___files/__results___10_0.png
/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/__results___files/__results___24_0.png
/kaggle/input/datasets/dhoogla/cicids2017/Benign-Monday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Bruteforce-Tuesday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Portscan-Friday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/WebAttacks-Thursday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/DoS-Wednesday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/DDoS-Friday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Infiltration-Thursday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Botnet-Friday-no-metadata.parquet

In [3]:
import glob

files = glob.glob("/kaggle/input/datasets/dhoogla/cicids2017/*.parquet")

print("Total files:", len(files))
print(files)

Total files: 8
['/kaggle/input/datasets/dhoogla/cicids2017/Benign-Monday-no-metadata.parquet', '/kaggle/input/datasets/dhoogla/cicids2017/Bruteforce-Tuesday-no-metadata.parquet', '/kaggle/input/datasets/dhoogla/cicids2017/Portscan-Friday-no-metadata.parquet', '/kaggle/input/datasets/dhoogla/cicids2017/WebAttacks-Thursday-no-metadata.parquet', '/kaggle/input/datasets/dhoogla/cicids2017/DoS-Wednesday-no-metadata.parquet', '/kaggle/input/datasets/dhoogla/cicids2017/DDoS-Friday-no-metadata.parquet', '/kaggle/input/datasets/dhoogla/cicids2017/Infiltration-Thursday-no-metadata.parquet', '/kaggle/input/datasets/dhoogla/cicids2017/Botnet-Friday-no-metadata.parquet']

In [4]:
import pandas as pd

df = pd.read_parquet(files[0])

print(df.shape)
df.head()

(458831, 78)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,4,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,6,1,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
2,6,3,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
3,6,1,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,6,609,7,4,484,414,233,0,69.14286,111.967896,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign

In [5]:
print(df.count())
print(len(df.columns))

Protocol                    458831
Flow Duration               458831
Total Fwd Packets           458831
Total Backward Packets      458831
Fwd Packets Length Total    458831
                             ...
Idle Mean                   458831
Idle Std                    458831
Idle Max                    458831
Idle Min                    458831
Label                       458831
Length: 78, dtype: int64
78

In [6]:
import pandas as pd

dfs = []

for file in files:
  
    print("Reading:", file)

    temp = pd.read_parquet(file)

    print("Shape:", temp.shape)

    dfs.append(temp)

Reading: /kaggle/input/datasets/dhoogla/cicids2017/Benign-Monday-no-metadata.parquet
Shape: (458831, 78)
Reading: /kaggle/input/datasets/dhoogla/cicids2017/Bruteforce-Tuesday-no-metadata.parquet
Shape: (389714, 78)
Reading: /kaggle/input/datasets/dhoogla/cicids2017/Portscan-Friday-no-metadata.parquet
Shape: (119522, 78)
Reading: /kaggle/input/datasets/dhoogla/cicids2017/WebAttacks-Thursday-no-metadata.parquet
Shape: (155820, 78)
Reading: /kaggle/input/datasets/dhoogla/cicids2017/DoS-Wednesday-no-metadata.parquet
Shape: (584991, 78)
Reading: /kaggle/input/datasets/dhoogla/cicids2017/DDoS-Friday-no-metadata.parquet
Shape: (221264, 78)
Reading: /kaggle/input/datasets/dhoogla/cicids2017/Infiltration-Thursday-no-metadata.parquet
Shape: (207630, 78)
Reading: /kaggle/input/datasets/dhoogla/cicids2017/Botnet-Friday-no-metadata.parquet
Shape: (176038, 78)

In [7]:
df = pd.concat(dfs, ignore_index=True)

print(df.shape)

(2313810, 78)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2313810 entries, 0 to 2313809
Data columns (total 78 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Protocol                  int8
 1   Flow Duration             int32
 2   Total Fwd Packets         int32
 3   Total Backward Packets    int32
 4   Fwd Packets Length Total  int32
 5   Bwd Packets Length Total  int32
 6   Fwd Packet Length Max     int16
 7   Fwd Packet Length Min     int16
 8   Fwd Packet Length Mean    float32
 9   Fwd Packet Length Std     float32
 10  Bwd Packet Length Max     int16
 11  Bwd Packet Length Min     int16
 12  Bwd Packet Length Mean    float32
 13  Bwd Packet Length Std     float32
 14  Flow Bytes/s              float64
 15  Flow Packets/s            float64
 16  Flow IAT Mean             float32
 17  Flow IAT Std              float32
 18  Flow IAT Max              int32
 19  Flow IAT Min              int32
 20  Fwd IAT Total             int32
 21  Fwd IAT Mean              float32
 22  Fwd IAT Std               float32
 23  Fwd IAT Max               int32
 24  Fwd IAT Min               int32
 25  Bwd IAT Total             int32
 26  Bwd IAT Mean              float32
 27  Bwd IAT Std               float32
 28  Bwd IAT Max               int32
 29  Bwd IAT Min               int32
 30  Fwd PSH Flags             int8
 31  Bwd PSH Flags             int8
 32  Fwd URG Flags             int8
 33  Bwd URG Flags             int8
 34  Fwd Header Length         int64
 35  Bwd Header Length         int32
 36  Fwd Packets/s             float32
 37  Bwd Packets/s             float32
 38  Packet Length Min         int16
 39  Packet Length Max         int16
 40  Packet Length Mean        float32
 41  Packet Length Std         float32
 42  Packet Length Variance    float32
 43  FIN Flag Count            int8
 44  SYN Flag Count            int8
 45  RST Flag Count            int8
 46  PSH Flag Count            int8
 47  ACK Flag Count            int8
 48  URG Flag Count            int8
 49  CWE Flag Count            int8
 50  ECE Flag Count            int8
 51  Down/Up Ratio             int16
 52  Avg Packet Size           float32
 53  Avg Fwd Segment Size      float32
 54  Avg Bwd Segment Size      float32
 55  Fwd Avg Bytes/Bulk        int8
 56  Fwd Avg Packets/Bulk      int8
 57  Fwd Avg Bulk Rate         int8
 58  Bwd Avg Bytes/Bulk        int8
 59  Bwd Avg Packets/Bulk      int8
 60  Bwd Avg Bulk Rate         int8
 61  Subflow Fwd Packets       int32
 62  Subflow Fwd Bytes         int32
 63  Subflow Bwd Packets       int32
 64  Subflow Bwd Bytes         int32
 65  Init Fwd Win Bytes        int32
 66  Init Bwd Win Bytes        int32
 67  Fwd Act Data Packets      int32
 68  Fwd Seg Size Min          int32
 69  Active Mean               float32
 70  Active Std                float32
 71  Active Max                int32
 72  Active Min                int32
 73  Idle Mean                 float32
 74  Idle Std                  float32
 75  Idle Max                  int32
 76  Idle Min                  int32
 77  Label                     object
dtypes: float32(22), float64(2), int16(7), int32(26), int64(1), int8(19), object(1)
memory usage: 567.1+ MB

In [9]:
import pandas as pd

df.describe()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,...,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2313810.0,2.313810e+06,2.313810e+06,2.313810e+06
mean,1.050673e+01,1.807575e+07,1.108391e+01,1.255334e+01,6.664045e+02,1.976976e+04,2.506291e+02,2.142396e+01,6.880505e+01,8.299155e+01,...,6.537630e+00,-3.360480e+03,9.977085e+04,5.032396e+04,1.874053e+05,7.131980e+04,10172609.0,6.164089e+05,1.063716e+07,9.688133e+06
std,5.416040e+00,3.640823e+07,8.291879e+02,1.103179e+03,1.105009e+04,2.503141e+06,7.855073e+02,6.334192e+01,2.018301e+02,3.062656e+02,...,7.039324e+02,1.200084e+06,7.124052e+05,4.322437e+05,1.131814e+06,6.375820e+05,26007036.0,5.067432e+06,2.656441e+07,2.550670e+07
min,0.000000e+00,-1.300000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,-5.368707e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.000000e+00,4.760000e+02,2.000000e+00,1.000000e+00,3.700000e+01,2.600000e+01,2.000000e+01,0.000000e+00,8.666667e+00,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.000000e+00,6.478300e+04,2.000000e+00,2.000000e+00,7.400000e+01,1.830000e+02,4.300000e+01,6.000000e+00,3.955556e+01,0.000000e+00,...,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.700000e+01,5.856948e+06,6.000000e+00,5.000000e+00,3.560000e+02,2.306000e+03,2.740000e+02,3.900000e+01,5.400000e+01,8.499406e+01,...,3.000000e+00,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
max,1.700000e+01,1.200000e+08,2.197590e+05,2.919220e+05,1.290000e+07,6.554530e+08,2.482000e+04,2.325000e+03,5.940857e+03,7.125597e+03,...,2.135570e+05,1.380000e+02,1.100000e+08,7.420000e+07,1.100000e+08,1.100000e+08,120000000.0,7.690000e+07,1.200000e+08,1.200000e+08

In [10]:
df.isnull().sum()

Protocol                    0
Flow Duration               0
Total Fwd Packets           0
Total Backward Packets      0
Fwd Packets Length Total    0
                           ..
Idle Mean                   0
Idle Std                    0
Idle Max                    0
Idle Min                    0
Label                       0
Length: 78, dtype: int64

In [11]:
print("Duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates()

Duplicate rows: 82004

In [12]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [13]:
df.describe()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,...,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2231806.0,2.231806e+06,2.231806e+06,2.231806e+06
mean,1.047114e+01,1.873981e+07,1.142387e+01,1.296894e+01,6.886546e+02,2.049333e+04,2.588665e+02,2.137632e+01,7.043391e+01,8.595025e+01,...,6.750848e+00,-3.484911e+03,1.034367e+05,5.217301e+04,1.942912e+05,7.394033e+04,10546386.0,6.390577e+05,1.102800e+07,1.004411e+07
std,5.409536e+00,3.690288e+07,8.442820e+02,1.123261e+03,1.125057e+04,2.548711e+06,7.985553e+02,6.423983e+01,2.056198e+02,3.116608e+02,...,7.167472e+02,1.221932e+06,7.249296e+05,4.399197e+05,1.151839e+06,6.490405e+05,26303076.0,5.156686e+06,2.696824e+07,2.590215e+07
min,0.000000e+00,-1.300000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,-5.368707e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.000000e+00,2.037000e+03,2.000000e+00,1.000000e+00,3.900000e+01,3.600000e+01,2.700000e+01,0.000000e+00,1.033333e+01,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.000000e+00,7.710950e+04,2.000000e+00,2.000000e+00,7.400000e+01,1.900000e+02,4.400000e+01,6.000000e+00,4.000000e+01,0.000000e+00,...,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.700000e+01,6.055697e+06,7.000000e+00,6.000000e+00,3.650000e+02,3.110000e+03,3.050000e+02,3.900000e+01,5.500000e+01,9.372896e+01,...,3.000000e+00,3.200000e+01,2.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,5132033.0,0.000000e+00,5.132054e+06,5.069420e+06
max,1.700000e+01,1.200000e+08,2.197590e+05,2.919220e+05,1.290000e+07,6.554530e+08,2.482000e+04,2.325000e+03,5.940857e+03,7.125597e+03,...,2.135570e+05,1.380000e+02,1.100000e+08,7.420000e+07,1.100000e+08,1.100000e+08,120000000.0,7.690000e+07,1.200000e+08,1.200000e+08

In [14]:
df = df[df["Flow Duration"] >= 0]

In [15]:
df.describe()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,2.231724e+06,2.231724e+06,2.231724e+06,2.231724e+06,2.231724e+06,2.231724e+06,2.231724e+06,2.231724e+06,2.231724e+06,2.231724e+06,...,2.231724e+06,2.231724e+06,2.231724e+06,2.231724e+06,2.231724e+06,2.231724e+06,2231724.0,2231724.0,2.231724e+06,2.231724e+06
mean,1.047131e+01,1.874049e+07,1.142425e+01,1.296938e+01,6.886797e+02,2.049409e+04,2.588759e+02,2.137696e+01,7.043634e+01,8.595339e+01,...,6.751096e+00,-3.485040e+03,1.034406e+05,5.217495e+04,1.942984e+05,7.394305e+04,10546771.0,639081.0,1.102841e+07,1.004448e+07
std,5.409567e+00,3.690338e+07,8.442975e+02,1.123282e+03,1.125077e+04,2.548757e+06,7.985685e+02,6.424092e+01,2.056230e+02,3.116660e+02,...,7.167604e+02,1.221955e+06,7.249426e+05,4.399276e+05,1.151860e+06,6.490523e+05,26303620.0,5156779.0,2.696866e+07,2.590255e+07
min,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,-5.368707e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00
25%,6.000000e+00,2.045000e+03,2.000000e+00,1.000000e+00,3.900000e+01,3.600000e+01,2.700000e+01,0.000000e+00,1.033333e+01,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00
50%,6.000000e+00,7.711800e+04,2.000000e+00,2.000000e+00,7.400000e+01,1.900000e+02,4.400000e+01,6.000000e+00,4.000000e+01,0.000000e+00,...,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00
75%,1.700000e+01,6.055980e+06,7.000000e+00,6.000000e+00,3.650000e+02,3.110000e+03,3.050000e+02,3.900000e+01,5.500000e+01,9.372896e+01,...,3.000000e+00,3.200000e+01,2.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,5132403.0,0.0,5.132432e+06,5.069580e+06
max,1.700000e+01,1.200000e+08,2.197590e+05,2.919220e+05,1.290000e+07,6.554530e+08,2.482000e+04,2.325000e+03,5.940857e+03,7.125597e+03,...,2.135570e+05,1.380000e+02,1.100000e+08,7.420000e+07,1.100000e+08,1.100000e+08,120000000.0,76900000.0,1.200000e+08,1.200000e+08

In [16]:
df["Label"].value_counts()

Label
Benign                        1895232
DoS Hulk                       172846
DDoS                           128014
DoS GoldenEye                   10286
FTP-Patator                      5931
DoS slowloris                    5385
DoS Slowhttptest                 5228
SSH-Patator                      3219
PortScan                         1956
Web Attack � Brute Force         1470
Bot                              1437
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [17]:
import joblib

xgb = joblib.load("/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/outputs/models/XGboost.pkl")
le = joblib.load("/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/label_encoder.pkl")
scaler = joblib.load("/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/minmax_scaler.pkl")
feature_columns = joblib.load("/kaggle/input/notebooks/hafsaferdousi5/3-feature-selection/outputs/features/feature_names.pkl")

print("Model classes:", xgb.n_classes_ if hasattr(xgb, "n_classes_") else "n/a")
print("Label encoder classes (2018):", list(le.classes_))
print("Number of training features:", len(feature_columns))

Model classes: 15
Label encoder classes (2018): ['Benign', 'Bot', 'Brute Force -Web', 'Brute Force -XSS', 'DDOS attack-HOIC', 'DDOS attack-LOIC-UDP', 'DDoS attacks-LOIC-HTTP', 'DoS attacks-GoldenEye', 'DoS attacks-Hulk', 'DoS attacks-SlowHTTPTest', 'DoS attacks-Slowloris', 'FTP-BruteForce', 'Infilteration', 'SQL Injection', 'SSH-Bruteforce']
Number of training features: 77

In [18]:
df["Label"].value_counts()

Label
Benign                        1895232
DoS Hulk                       172846
DDoS                           128014
DoS GoldenEye                   10286
FTP-Patator                      5931
DoS slowloris                    5385
DoS Slowhttptest                 5228
SSH-Patator                      3219
PortScan                         1956
Web Attack � Brute Force         1470
Bot                              1437
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [19]:
print("CIC-IDS2017 labels:")
print(df["Label"].unique())

print("\n2018 Label Encoder classes:")
print(le.classes_)

print("\nSelected features:")
print(feature_columns)

CIC-IDS2017 labels:
['Benign' 'FTP-Patator' 'SSH-Patator' 'PortScan'
 'Web Attack � Brute Force' 'Web Attack � XSS'
 'Web Attack � Sql Injection' 'DoS slowloris' 'DoS Slowhttptest'
 'DoS Hulk' 'DoS GoldenEye' 'Heartbleed' 'DDoS' 'Infiltration' 'Bot']

2018 Label Encoder classes:
['Benign' 'Bot' 'Brute Force -Web' 'Brute Force -XSS' 'DDOS attack-HOIC'
 'DDOS attack-LOIC-UDP' 'DDoS attacks-LOIC-HTTP' 'DoS attacks-GoldenEye'
 'DoS attacks-Hulk' 'DoS attacks-SlowHTTPTest' 'DoS attacks-Slowloris'
 'FTP-BruteForce' 'Infilteration' 'SQL Injection' 'SSH-Bruteforce']

Selected features:
['Protocol', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 'Fwd Packets Length Total', 'Bwd Packets Length Total', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Packet Length Min', 'Packet Length Max', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Avg Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init Fwd Win Bytes', 'Init Bwd Win Bytes', 'Fwd Act Data Packets', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min']

In [20]:
# Check selected features
missing_features = [
    f for f in feature_columns
    if f not in df.columns
]

print("Total selected features:", len(feature_columns))
print("Missing features:", len(missing_features))

if missing_features:
    print("\nMissing features:")
    for f in missing_features:
        print(f)
else:
    print("\n All selected features are available.")

Total selected features: 77
Missing features: 0

 All selected features are available.

In [21]:
import numpy as np
import pandas as pd

# Selected features from the 2018 pipeline
X_cross = df[feature_columns].copy()
y_cross_original = df["Label"].copy()

# Clean test data
X_cross = X_cross.replace([np.inf, -np.inf], np.nan)
X_cross = X_cross.fillna(0)

print("X_cross shape:", X_cross.shape)
print("y_cross shape:", y_cross_original.shape)

X_cross shape: (2231724, 77)
y_cross shape: (2231724,)

In [22]:
missing_features = [
    f for f in feature_columns
    if f not in df.columns
]

print("Selected features:", len(feature_columns))
print("Missing features:", len(missing_features))

if missing_features:
    print("\nMissing features:")
    for f in missing_features:
        print(f)
else:
    print("\n✓ All selected features are available.")

Selected features: 77
Missing features: 0

✓ All selected features are available.

In [23]:
X_cross_scaled = scaler.transform(X_cross)

print("Scaled test shape:", X_cross_scaled.shape)

Scaled test shape: (2231724, 77)

In [24]:
y_pred_encoded = xgb.predict(X_cross_scaled)

print("Prediction shape:", y_pred_encoded.shape)
print("Encoded predictions:", np.unique(y_pred_encoded))

Prediction shape: (2231724,)
Encoded predictions: [ 0  1  2  3  4  5  6  7  8 10 12 13 14]

In [25]:
y_pred_2018 = le.inverse_transform(
    y_pred_encoded.astype(int)
)

print("\nPredicted 2018 labels:")
print(np.unique(y_pred_2018))

Predicted 2018 labels:
['Benign' 'Bot' 'Brute Force -Web' 'Brute Force -XSS' 'DDOS attack-HOIC'
 'DDOS attack-LOIC-UDP' 'DDoS attacks-LOIC-HTTP' 'DoS attacks-GoldenEye'
 'DoS attacks-Hulk' 'DoS attacks-Slowloris' 'Infilteration'
 'SQL Injection' 'SSH-Bruteforce']

In [26]:
def map_2017_label(label):
    label = str(label).strip()

    mapping = {
        "Benign": "Benign",
        "Bot": "Bot",

        "FTP-Patator": "FTP",
        "SSH-Patator": "SSH",

        "Web Attack � Brute Force": "Brute Force",
        "Web Attack � XSS": "XSS",
        "Web Attack � Sql Injection": "SQL Injection",

        "DoS slowloris": "DoS",
        "DoS Slowhttptest": "DoS",
        "DoS Hulk": "DoS",
        "DoS GoldenEye": "DoS",

        "DDoS": "DDoS",

        "Infiltration": "Infiltration",

        # No corresponding 2018 model class
        "PortScan": "Other",
        "Heartbleed": "Other"
    }

    return mapping.get(label, "Other")


y_true_harmonized = y_cross_original.apply(map_2017_label)

print("2017 harmonized labels:")
print(y_true_harmonized.value_counts())

2017 harmonized labels:
Label
Benign           1895232
DoS               193745
DDoS              128014
FTP                 5931
SSH                 3219
Other               1967
Brute Force         1470
Bot                 1437
XSS                  652
Infiltration          36
SQL Injection         21
Name: count, dtype: int64

In [27]:
def map_2018_label(label):
    label = str(label).strip()

    mapping = {
        "Benign": "Benign",
        "Bot": "Bot",

        "FTP-BruteForce": "FTP",
        "SSH-Bruteforce": "SSH",

        "Brute Force -Web": "Brute Force",
        "Brute Force -XSS": "XSS",

        "SQL Injection": "SQL Injection",

        "DoS attacks-GoldenEye": "DoS",
        "DoS attacks-Hulk": "DoS",
        "DoS attacks-SlowHTTPTest": "DoS",
        "DoS attacks-Slowloris": "DoS",

        "DDOS attack-HOIC": "DDoS",
        "DDOS attack-LOIC-UDP": "DDoS",
        "DDoS attacks-LOIC-HTTP": "DDoS",

        "Infilteration": "Infiltration"
    }

    return mapping.get(label, "Other")


y_pred_harmonized = pd.Series(y_pred_2018).apply(
    map_2018_label
)

print("2018 prediction labels:")
print(y_pred_harmonized.value_counts())

2018 prediction labels:
Benign           2165537
DoS                59557
DDoS                3155
Infiltration        3091
SSH                  367
XSS                    7
SQL Injection          4
Brute Force            3
Bot                    3
Name: count, dtype: int64

In [28]:
print("Actual labels:")
print(sorted(y_true_harmonized.unique()))

print("\nPredicted labels:")
print(sorted(y_pred_harmonized.unique()))

Actual labels:
['Benign', 'Bot', 'Brute Force', 'DDoS', 'DoS', 'FTP', 'Infiltration', 'Other', 'SQL Injection', 'SSH', 'XSS']

Predicted labels:
['Benign', 'Bot', 'Brute Force', 'DDoS', 'DoS', 'Infiltration', 'SQL Injection', 'SSH', 'XSS']

In [29]:
# Reset indexes so both Series have the same positional index
y_true_harmonized = y_true_harmonized.reset_index(drop=True)
y_pred_harmonized = y_pred_harmonized.reset_index(drop=True)

# Keep only common-label samples
common_mask = y_true_harmonized != "Other"

y_true_common = y_true_harmonized[common_mask].reset_index(drop=True)
y_pred_common = y_pred_harmonized[common_mask].reset_index(drop=True)

print("Original test samples:", len(y_true_harmonized))
print("Common-label samples:", len(y_true_common))
print("Excluded samples:", len(y_true_harmonized) - len(y_true_common))

Original test samples: 2231724
Common-label samples: 2229757
Excluded samples: 1967

In [30]:
print("Actual labels:")
print(sorted(y_true_harmonized.unique()))

print("\nPredicted labels:")
print(sorted(y_pred_harmonized.unique()))

Actual labels:
['Benign', 'Bot', 'Brute Force', 'DDoS', 'DoS', 'FTP', 'Infiltration', 'Other', 'SQL Injection', 'SSH', 'XSS']

Predicted labels:
['Benign', 'Bot', 'Brute Force', 'DDoS', 'DoS', 'Infiltration', 'SQL Injection', 'SSH', 'XSS']

In [31]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

accuracy = accuracy_score(
    y_true_common,
    y_pred_common
)

precision = precision_score(
    y_true_common,
    y_pred_common,
    average="weighted",
    zero_division=0
)

recall = recall_score(
    y_true_common,
    y_pred_common,
    average="weighted",
    zero_division=0
)

f1 = f1_score(
    y_true_common,
    y_pred_common,
    average="weighted",
    zero_division=0
)

print("\n========================================")
print(" MULTICLASS CROSS-DATASET RESULTS")
print(" Train: CSE-CIC-IDS2018")
print(" Test : CIC-IDS2017")
print("========================================")

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-score : {f1:.4f}")

========================================
 MULTICLASS CROSS-DATASET RESULTS
 Train: CSE-CIC-IDS2018
 Test : CIC-IDS2017
========================================
Accuracy : 0.8720
Precision: 0.8533
Recall   : 0.8720
F1-score : 0.8301

In [32]:
print("\nClassification Report:\n")

print(
    classification_report(
        y_true_common,
        y_pred_common,
        zero_division=0
    )
)

Classification Report:

               precision    recall  f1-score   support

       Benign       0.87      1.00      0.93   1895232
          Bot       0.00      0.00      0.00      1437
  Brute Force       0.00      0.00      0.00      1470
         DDoS       0.53      0.01      0.03    128014
          DoS       0.94      0.29      0.44    193745
          FTP       0.00      0.00      0.00      5931
 Infiltration       0.00      0.00      0.00        36
SQL Injection       0.00      0.00      0.00        21
          SSH       0.00      0.00      0.00      3219
          XSS       0.14      0.00      0.00       652

     accuracy                           0.87   2229757
    macro avg       0.25      0.13      0.14   2229757
 weighted avg       0.85      0.87      0.83   2229757

In [37]:
import joblib

# Load models
xgb = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/outputs/models/XGboost.pkl"
)

rf = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/outputs/models/random_forest.pkl"
)

lgbm = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/outputs/models/lightgbm_leaves31.pkl"
)

catb = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/outputs/models/catboost.pkl"
)

# Preprocessing objects
le = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/label_encoder.pkl"
)

scaler = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/label_encoder.pkl"
)

feature_columns = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/3-feature-selection/outputs/features/feature_names.pkl"
)

print("Models loaded successfully!")
print("Selected features:", len(feature_columns))
print("2018 classes:", list(le.classes_))

Models loaded successfully!
Selected features: 77
2018 classes: ['Benign', 'Bot', 'Brute Force -Web', 'Brute Force -XSS', 'DDOS attack-HOIC', 'DDOS attack-LOIC-UDP', 'DDoS attacks-LOIC-HTTP', 'DoS attacks-GoldenEye', 'DoS attacks-Hulk', 'DoS attacks-SlowHTTPTest', 'DoS attacks-Slowloris', 'FTP-BruteForce', 'Infilteration', 'SQL Injection', 'SSH-Bruteforce']

In [ ]:
# Load models
xgb = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/outputs/models/XGboost.pkl"
)

rf = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/2-model-rf/outputs/models/random_forest.pkl"
)

lgbm = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/2-2model-lightgbm/outputs/models/lightgbm_leaves31.pkl"
)

catb = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/02-2model-catboost/outputs/models/catboost.pkl"
)

# Preprocessing objects
le = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/label_encoder.pkl"
)

scaler = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/label_encoder.pkl"
)

feature_columns = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/3-feature-selection/outputs/features/feature_names.pkl"
)

print("Models loaded successfully!")
print("Selected features:", len(feature_columns))
print("2018 classes:", list(le.classes_))

In [ ]:
/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/minmax_scaler.pkl

In [38]:
scaler = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/minmax_scaler.pkl"
)

In [39]:

print("Label encoder:", type(le))
print("Scaler:", type(scaler))
print("Features:", len(feature_columns))

Label encoder: <class 'sklearn.preprocessing._label.LabelEncoder'>
Scaler: <class 'sklearn.preprocessing._data.MinMaxScaler'>
Features: 77

In [ ]:
import joblib

xgb = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/2-2xgboost/outputs/models/XGboost.pkl"
)

le = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/label_encoder.pkl"
)

scaler = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/01-data-preprocessing/outputs/models/minmax_scaler.pkl"
)

feature_columns = joblib.load(
    "/kaggle/input/notebooks/hafsaferdousi5/3-feature-selection/outputs/features/feature_names.pkl"
)

print("Label encoder:", type(le))
print("Scaler:", type(scaler))
print("Features:", len(feature_columns))

In [40]:
X_cross = df[feature_columns].copy()
y_cross_original = df["Label"].copy()

X_cross = X_cross.replace([np.inf, -np.inf], np.nan)
X_cross = X_cross.fillna(0)

X_cross_scaled = scaler.transform(X_cross)

print("Cross-dataset test shape:", X_cross_scaled.shape)

Cross-dataset test shape: (2231724, 77)

In [41]:
models = {
    "XGBoost": xgb,
    "Random Forest": rf,
    "LightGBM": lgbm,
    "CatBoost": catb
}

predictions = {}

for name, model in models.items():

    print(f"\nRunning {name}...")

    pred_encoded = model.predict(X_cross_scaled)

    # Handle models that return shape (n, 1)
    pred_encoded = np.asarray(pred_encoded).reshape(-1)

    predictions[name] = le.inverse_transform(
        pred_encoded.astype(int)
    )

    print(f"{name} completed.")
    print("Predicted classes:", np.unique(predictions[name]))

Running XGBoost...
XGBoost completed.
Predicted classes: ['Benign' 'Bot' 'Brute Force -Web' 'Brute Force -XSS' 'DDOS attack-HOIC'
 'DDOS attack-LOIC-UDP' 'DDoS attacks-LOIC-HTTP' 'DoS attacks-GoldenEye'
 'DoS attacks-Hulk' 'DoS attacks-Slowloris' 'Infilteration'
 'SQL Injection' 'SSH-Bruteforce']

Running Random Forest...
Random Forest completed.
Predicted classes: ['Benign' 'Bot' 'Brute Force -Web' 'DDOS attack-HOIC'
 'DDoS attacks-LOIC-HTTP' 'DoS attacks-GoldenEye' 'DoS attacks-Hulk'
 'DoS attacks-SlowHTTPTest' 'DoS attacks-Slowloris' 'FTP-BruteForce'
 'Infilteration' 'SQL Injection' 'SSH-Bruteforce']

Running LightGBM...

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

LightGBM completed.
Predicted classes: ['Benign' 'Bot' 'Brute Force -Web' 'Brute Force -XSS' 'DDOS attack-HOIC'
 'DDOS attack-LOIC-UDP' 'DDoS attacks-LOIC-HTTP' 'DoS attacks-GoldenEye'
 'DoS attacks-Hulk' 'DoS attacks-SlowHTTPTest' 'DoS attacks-Slowloris'
 'FTP-BruteForce' 'Infilteration' 'SQL Injection' 'SSH-Bruteforce']

Running CatBoost...
CatBoost completed.
Predicted classes: ['Benign' 'Brute Force -XSS' 'DDOS attack-HOIC' 'DDoS attacks-LOIC-HTTP'
 'DoS attacks-GoldenEye' 'DoS attacks-Hulk' 'DoS attacks-Slowloris'
 'Infilteration' 'SSH-Bruteforce']

In [42]:
def map_2018_label(label):
    label = str(label).strip()

    mapping = {
        "Benign": "Benign",
        "Bot": "Bot",

        "FTP-BruteForce": "FTP",
        "SSH-Bruteforce": "SSH",

        "Brute Force -Web": "Brute Force",
        "Brute Force -XSS": "XSS",

        "SQL Injection": "SQL Injection",

        "DoS attacks-GoldenEye": "DoS",
        "DoS attacks-Hulk": "DoS",
        "DoS attacks-SlowHTTPTest": "DoS",
        "DoS attacks-Slowloris": "DoS",

        "DDOS attack-HOIC": "DDoS",
        "DDOS attack-LOIC-UDP": "DDoS",
        "DDoS attacks-LOIC-HTTP": "DDoS",

        "Infilteration": "Infiltration"
    }

    return mapping.get(label, "Other")

In [43]:
predictions_harmonized = {}

for name, preds in predictions.items():

    predictions_harmonized[name] = pd.Series(preds).apply(
        map_2018_label
    )

    print(f"\n{name} prediction labels:")
    print(predictions_harmonized[name].value_counts())

XGBoost prediction labels:
Benign           2165537
DoS                59557
DDoS                3155
Infiltration        3091
SSH                  367
XSS                    7
SQL Injection          4
Brute Force            3
Bot                    3
Name: count, dtype: int64

Random Forest prediction labels:
Benign           2215440
DoS                10453
SSH                 3824
Infiltration        1491
DDoS                 474
FTP                   21
Bot                   16
SQL Injection          3
Brute Force            2
Name: count, dtype: int64

LightGBM prediction labels:
Benign           1980027
Infiltration       74777
SSH                52289
SQL Injection      44285
DoS                43346
DDoS               26563
Bot                 8222
FTP                 1339
XSS                  848
Brute Force           28
Name: count, dtype: int64

CatBoost prediction labels:
Benign          2211491
DoS               19624
DDoS                349
SSH                 136
Infiltration        123
XSS                   1
Name: count, dtype: int64

In [44]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef
)

# Actual labels
y_true_harmonized = y_true_harmonized.reset_index(drop=True)

# Keep only samples with labels represented in the 2018 model
common_mask = y_true_harmonized != "Other"

y_true_common = y_true_harmonized[
    common_mask
].reset_index(drop=True)

results = []

for name, preds in predictions_harmonized.items():

    preds = preds.reset_index(drop=True)

    y_pred_common = preds[
        common_mask
    ].reset_index(drop=True)

    accuracy = accuracy_score(
        y_true_common,
        y_pred_common
    )

    precision = precision_score(
        y_true_common,
        y_pred_common,
        average="weighted",
        zero_division=0
    )

    recall = recall_score(
        y_true_common,
        y_pred_common,
        average="weighted",
        zero_division=0
    )

    f1 = f1_score(
        y_true_common,
        y_pred_common,
        average="weighted",
        zero_division=0
    )

    # Matthews Correlation Coefficient
    mcc = matthews_corrcoef(
        y_true_common,
        y_pred_common
    )

    results.append({
        "Model": name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1-score": f1,
        "MCC": mcc
    })

results_df = pd.DataFrame(results)

print("\n==============================================")
print(" CROSS-DATASET MULTICLASS RESULTS")
print(" Train: CSE-CIC-IDS2018")
print(" Test : CIC-IDS2017")
print("==============================================")

display(
    results_df.style.format({
        "Accuracy": "{:.4f}",
        "Precision": "{:.4f}",
        "Recall": "{:.4f}",
        "F1-score": "{:.4f}",
        "MCC": "{:.4f}"
    })
)

==============================================
 CROSS-DATASET MULTICLASS RESULTS
 Train: CSE-CIC-IDS2018
 Test : CIC-IDS2017
==============================================

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    roc_auc_score
)

# Actual labels
y_true_harmonized = y_true_harmonized.reset_index(drop=True)

# Keep only samples with labels represented in the 2018 model
common_mask = y_true_harmonized != "Other"

y_true_common = y_true_harmonized[
    common_mask
].reset_index(drop=True)

results = []

for name, preds in predictions_harmonized.items():

    # Predicted labels
    preds = preds.reset_index(drop=True)

    y_pred_common = preds[
        common_mask
    ].reset_index(drop=True)

    # -----------------------------
    # Classification metrics
    # -----------------------------
    accuracy = accuracy_score(
        y_true_common,
        y_pred_common
    )

    precision = precision_score(
        y_true_common,
        y_pred_common,
        average="weighted",
        zero_division=0
    )

    recall = recall_score(
        y_true_common,
        y_pred_common,
        average="weighted",
        zero_division=0
    )

    f1 = f1_score(
        y_true_common,
        y_pred_common,
        average="weighted",
        zero_division=0
    )

    # -----------------------------
    # Matthews Correlation Coefficient
    # -----------------------------
    mcc = matthews_corrcoef(
        y_true_common,
        y_pred_common
    )

    # -----------------------------
    # Multiclass ROC-AUC
    # -----------------------------
    model = models[name]

    y_proba = model.predict_proba(X_cross_scaled)

    # Apply the same mask used for evaluation
    y_proba_common = y_proba[
        common_mask.values
    ]

    # Model classes -> original labels
    model_classes = le.inverse_transform(
        np.arange(len(model.classes_))
    )

    # Harmonize model class names
    model_classes_harmonized = np.array([
        map_2018_label(label)
        for label in model_classes
    ])

    # Get the classes actually present after harmonization
    auc_classes = np.unique(
        y_true_common
    )

    # Create probability matrix for the common classes
    auc_proba = np.zeros(
        (len(y_true_common), len(auc_classes))
    )

    for i, cls in enumerate(auc_classes):

        matching = np.where(
            model_classes_harmonized == cls
        )[0]

        if len(matching) > 0:
            auc_proba[:, i] = y_proba_common[:, matching[0]]

    # Normalize probabilities
    row_sums = auc_proba.sum(axis=1)
    valid_rows = row_sums > 0

    auc_proba[valid_rows] = (
        auc_proba[valid_rows]
        / row_sums[valid_rows, None]
    )

    # Encode true labels
    y_true_auc = pd.Categorical(
        y_true_common,
        categories=auc_classes
    ).codes

    # Calculate weighted multiclass ROC-AUC
    try:
        auc = roc_auc_score(
            y_true_auc,
            auc_proba,
            multi_class="ovr",
            average="weighted",
            labels=np.arange(len(auc_classes))
        )
    except ValueError:
        auc = np.nan

    # -----------------------------
    # Store results
    # -----------------------------
    results.append({
        "Model": name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1-score": f1,
        "MCC": mcc,
        "AUC": auc
    })


# Final results table
results_df = pd.DataFrame(results)

print("\n==============================================")
print(" CROSS-DATASET MULTICLASS RESULTS")
print(" Train: CSE-CIC-IDS2018")
print(" Test : CIC-IDS2017")
print("==============================================")

display(
    results_df.style.format({
        "Accuracy": "{:.4f}",
        "Precision": "{:.4f}",
        "Recall": "{:.4f}",
        "F1-score": "{:.4f}",
        "MCC": "{:.4f}",
        "AUC": "{:.4f}"
    })
)