# Dataset

In [1]:
import numpy as np
import pandas as pd
import os
import glob

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        if filename.endswith(".parquet"):
            print(os.path.join(dirname, filename))

/kaggle/input/datasets/dhoogla/cicids2017/Benign-Monday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Bruteforce-Tuesday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Portscan-Friday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/WebAttacks-Thursday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/DoS-Wednesday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/DDoS-Friday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Infiltration-Thursday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Botnet-Friday-no-metadata.parquet

In [2]:
files = glob.glob("/kaggle/input/**/*.parquet", recursive=True)

# Only files belonging to this CICIDS2017 dataset
expected_names = [
    "Benign-Monday-no-metadata.parquet",
    "Botnet-Friday-no-metadata.parquet",
    "Bruteforce-Tuesday-no-metadata.parquet",
    "DDoS-Friday-no-metadata.parquet",
    "DoS-Wednesday-no-metadata.parquet",
    "Infiltration-Thursday-no-metadata.parquet",
    "Portscan-Friday-no-metadata.parquet",
    "WebAttacks-Thursday-no-metadata.parquet"
]

files = [
    f for f in files
    if os.path.basename(f) in expected_names
]

files = sorted(files)

print("Total files:", len(files))

for f in files:
    print(f)

Total files: 8
/kaggle/input/datasets/dhoogla/cicids2017/Benign-Monday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Botnet-Friday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Bruteforce-Tuesday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/DDoS-Friday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/DoS-Wednesday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Infiltration-Thursday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/Portscan-Friday-no-metadata.parquet
/kaggle/input/datasets/dhoogla/cicids2017/WebAttacks-Thursday-no-metadata.parquet

In [3]:
df_temp = pd.read_parquet(files[0])

print("Shape:", df_temp.shape)
df_temp.head()

Shape: (458831, 78)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,4,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,6,1,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
2,6,3,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
3,6,1,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,6,609,7,4,484,414,233,0,69.14286,111.967896,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign

In [4]:
print(df_temp.count())
print("\nTotal columns:", len(df_temp.columns))

Protocol                    458831
Flow Duration               458831
Total Fwd Packets           458831
Total Backward Packets      458831
Fwd Packets Length Total    458831
                             ...
Idle Mean                   458831
Idle Std                    458831
Idle Max                    458831
Idle Min                    458831
Label                       458831
Length: 78, dtype: int64

Total columns: 78

In [5]:
dfs = []

for file in files:
    print("=" * 80)
    print("Reading:", os.path.basename(file))

    temp = pd.read_parquet(file)

    print("Shape:", temp.shape)

    dfs.append(temp)

================================================================================
Reading: Benign-Monday-no-metadata.parquet
Shape: (458831, 78)
================================================================================
Reading: Botnet-Friday-no-metadata.parquet
Shape: (176038, 78)
================================================================================
Reading: Bruteforce-Tuesday-no-metadata.parquet
Shape: (389714, 78)
================================================================================
Reading: DDoS-Friday-no-metadata.parquet
Shape: (221264, 78)
================================================================================
Reading: DoS-Wednesday-no-metadata.parquet
Shape: (584991, 78)
================================================================================
Reading: Infiltration-Thursday-no-metadata.parquet
Shape: (207630, 78)
================================================================================
Reading: Portscan-Friday-no-metadata.parquet
Shape: (119522, 78)
================================================================================
Reading: WebAttacks-Thursday-no-metadata.parquet
Shape: (155820, 78)

In [6]:
df = pd.concat(dfs, ignore_index=True)

print("Combined dataset shape:", df.shape)

Combined dataset shape: (2313810, 78)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2313810 entries, 0 to 2313809
Data columns (total 78 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Protocol                  int8
 1   Flow Duration             int32
 2   Total Fwd Packets         int32
 3   Total Backward Packets    int32
 4   Fwd Packets Length Total  int32
 5   Bwd Packets Length Total  int32
 6   Fwd Packet Length Max     int16
 7   Fwd Packet Length Min     int16
 8   Fwd Packet Length Mean    float32
 9   Fwd Packet Length Std     float32
 10  Bwd Packet Length Max     int16
 11  Bwd Packet Length Min     int16
 12  Bwd Packet Length Mean    float32
 13  Bwd Packet Length Std     float32
 14  Flow Bytes/s              float64
 15  Flow Packets/s            float64
 16  Flow IAT Mean             float32
 17  Flow IAT Std              float32
 18  Flow IAT Max              int32
 19  Flow IAT Min              int32
 20  Fwd IAT Total             int32
 21  Fwd IAT Mean              float32
 22  Fwd IAT Std               float32
 23  Fwd IAT Max               int32
 24  Fwd IAT Min               int32
 25  Bwd IAT Total             int32
 26  Bwd IAT Mean              float32
 27  Bwd IAT Std               float32
 28  Bwd IAT Max               int32
 29  Bwd IAT Min               int32
 30  Fwd PSH Flags             int8
 31  Bwd PSH Flags             int8
 32  Fwd URG Flags             int8
 33  Bwd URG Flags             int8
 34  Fwd Header Length         int64
 35  Bwd Header Length         int32
 36  Fwd Packets/s             float32
 37  Bwd Packets/s             float32
 38  Packet Length Min         int16
 39  Packet Length Max         int16
 40  Packet Length Mean        float32
 41  Packet Length Std         float32
 42  Packet Length Variance    float32
 43  FIN Flag Count            int8
 44  SYN Flag Count            int8
 45  RST Flag Count            int8
 46  PSH Flag Count            int8
 47  ACK Flag Count            int8
 48  URG Flag Count            int8
 49  CWE Flag Count            int8
 50  ECE Flag Count            int8
 51  Down/Up Ratio             int16
 52  Avg Packet Size           float32
 53  Avg Fwd Segment Size      float32
 54  Avg Bwd Segment Size      float32
 55  Fwd Avg Bytes/Bulk        int8
 56  Fwd Avg Packets/Bulk      int8
 57  Fwd Avg Bulk Rate         int8
 58  Bwd Avg Bytes/Bulk        int8
 59  Bwd Avg Packets/Bulk      int8
 60  Bwd Avg Bulk Rate         int8
 61  Subflow Fwd Packets       int32
 62  Subflow Fwd Bytes         int32
 63  Subflow Bwd Packets       int32
 64  Subflow Bwd Bytes         int32
 65  Init Fwd Win Bytes        int32
 66  Init Bwd Win Bytes        int32
 67  Fwd Act Data Packets      int32
 68  Fwd Seg Size Min          int32
 69  Active Mean               float32
 70  Active Std                float32
 71  Active Max                int32
 72  Active Min                int32
 73  Idle Mean                 float32
 74  Idle Std                  float32
 75  Idle Max                  int32
 76  Idle Min                  int32
 77  Label                     object
dtypes: float32(22), float64(2), int16(7), int32(26), int64(1), int8(19), object(1)
memory usage: 567.1+ MB

In [8]:
df.describe()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,...,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2313810.0,2.313810e+06,2.313810e+06,2.313810e+06
mean,1.050673e+01,1.807575e+07,1.108391e+01,1.255334e+01,6.664045e+02,1.976976e+04,2.506291e+02,2.142396e+01,6.880502e+01,8.299153e+01,...,6.537630e+00,-3.360480e+03,9.977085e+04,5.032398e+04,1.874053e+05,7.131980e+04,10172613.0,6.164088e+05,1.063716e+07,9.688133e+06
std,5.416040e+00,3.640823e+07,8.291879e+02,1.103179e+03,1.105009e+04,2.503141e+06,7.855073e+02,6.334192e+01,2.017213e+02,3.041364e+02,...,7.039324e+02,1.200084e+06,7.120588e+05,4.322412e+05,1.131814e+06,6.375820e+05,25991066.0,5.065188e+06,2.656441e+07,2.550670e+07
min,0.000000e+00,-1.300000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,-5.368707e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.000000e+00,4.760000e+02,2.000000e+00,1.000000e+00,3.700000e+01,2.600000e+01,2.000000e+01,0.000000e+00,8.666667e+00,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.000000e+00,6.478300e+04,2.000000e+00,2.000000e+00,7.400000e+01,1.830000e+02,4.300000e+01,6.000000e+00,3.955556e+01,0.000000e+00,...,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.700000e+01,5.856948e+06,6.000000e+00,5.000000e+00,3.560000e+02,2.306000e+03,2.740000e+02,3.900000e+01,5.400000e+01,8.499406e+01,...,3.000000e+00,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
max,1.700000e+01,1.200000e+08,2.197590e+05,2.919220e+05,1.290000e+07,6.554530e+08,2.482000e+04,2.325000e+03,5.940857e+03,7.125597e+03,...,2.135570e+05,1.380000e+02,1.100000e+08,7.420000e+07,1.100000e+08,1.100000e+08,120000000.0,7.690000e+07,1.200000e+08,1.200000e+08

# Preprocessing

## 1. Missing Value Check

In [9]:
missing = df.isnull().sum()

print(missing[missing > 0])
print("\nTotal missing values:", missing.sum())

Series([], dtype: int64)

Total missing values: 0

## 2. Infinite Value Check

In [10]:
numeric_cols = df.select_dtypes(include=np.number).columns

inf_count = np.isinf(df[numeric_cols]).sum()

print(inf_count[inf_count > 0])
print("\nTotal infinity values:", inf_count.sum())

Series([], dtype: int64)

Total infinity values: 0

## 3. Data Cleaning

In [11]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [12]:
print("Rows before cleaning:", len(df))

df = df.dropna().reset_index(drop=True)

print("Rows after cleaning:", len(df))

Rows before cleaning: 2313810
Rows after cleaning: 2313810

## 4. Duplicate Removal

In [13]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 82004

In [14]:
df = df.drop_duplicates().reset_index(drop=True)

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (2231806, 78)

In [15]:
df.describe()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,...,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2.231806e+06,2231806.0,2.231806e+06,2.231806e+06,2.231806e+06
mean,1.047114e+01,1.873981e+07,1.142387e+01,1.296894e+01,6.886546e+02,2.049333e+04,2.588665e+02,2.137632e+01,7.043387e+01,8.595027e+01,...,6.750848e+00,-3.484911e+03,1.034368e+05,5.217305e+04,1.942912e+05,7.394033e+04,10546389.0,6.390578e+05,1.102800e+07,1.004411e+07
std,5.409536e+00,3.690288e+07,8.442820e+02,1.123261e+03,1.125057e+04,2.548711e+06,7.985553e+02,6.423983e+01,2.057675e+02,3.095137e+02,...,7.167472e+02,1.221932e+06,7.245676e+05,4.399167e+05,1.151839e+06,6.490405e+05,26287106.0,5.154270e+06,2.696824e+07,2.590215e+07
min,0.000000e+00,-1.300000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,-5.368707e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.000000e+00,2.037000e+03,2.000000e+00,1.000000e+00,3.900000e+01,3.600000e+01,2.700000e+01,0.000000e+00,1.033333e+01,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.000000e+00,7.710950e+04,2.000000e+00,2.000000e+00,7.400000e+01,1.900000e+02,4.400000e+01,6.000000e+00,4.000000e+01,0.000000e+00,...,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.700000e+01,6.055697e+06,7.000000e+00,6.000000e+00,3.650000e+02,3.110000e+03,3.050000e+02,3.900000e+01,5.500000e+01,9.372896e+01,...,3.000000e+00,3.200000e+01,2.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,5132033.0,0.000000e+00,5.132054e+06,5.069420e+06
max,1.700000e+01,1.200000e+08,2.197590e+05,2.919220e+05,1.290000e+07,6.554530e+08,2.482000e+04,2.325000e+03,5.940857e+03,7.125597e+03,...,2.135570e+05,1.380000e+02,1.100000e+08,7.420000e+07,1.100000e+08,1.100000e+08,120000000.0,7.690000e+07,1.200000e+08,1.200000e+08

## 5. Flow Duration Validation

In [16]:
if "Flow Duration" in df.columns:

    print("Negative Flow Duration:",
          (df["Flow Duration"] < 0).sum())

    df = df[df["Flow Duration"] >= 0].reset_index(drop=True)

Negative Flow Duration: 82

## 6. Number of Target Classes

In [17]:
print("Number of classes:", df["Label"].nunique())

print("\nClasses:")

for label in sorted(df["Label"].astype(str).unique()):
    print(label)

Number of classes: 15

Classes:
Benign
Bot
DDoS
DoS GoldenEye
DoS Hulk
DoS Slowhttptest
DoS slowloris
FTP-Patator
Heartbleed
Infiltration
PortScan
SSH-Patator
Web Attack � Brute Force
Web Attack � Sql Injection
Web Attack � XSS

## 7. Class Distribution Analysis

In [18]:
class_counts = df["Label"].value_counts()

print(class_counts)

Label
Benign                        1895232
DoS Hulk                       172846
DDoS                           128014
DoS GoldenEye                   10286
FTP-Patator                      5931
DoS slowloris                    5385
DoS Slowhttptest                 5228
SSH-Patator                      3219
PortScan                         1956
Web Attack � Brute Force         1470
Bot                              1437
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [19]:
df_before = df.copy()

## 8. Label Encoding

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Label"] = le.fit_transform(
    df["Label"].astype(str)
)

print("Class Mapping:")

for i, class_name in enumerate(le.classes_):
    print(i, "->", class_name)

Class Mapping:
0 -> Benign
1 -> Bot
2 -> DDoS
3 -> DoS GoldenEye
4 -> DoS Hulk
5 -> DoS Slowhttptest
6 -> DoS slowloris
7 -> FTP-Patator
8 -> Heartbleed
9 -> Infiltration
10 -> PortScan
11 -> SSH-Patator
12 -> Web Attack � Brute Force
13 -> Web Attack � Sql Injection
14 -> Web Attack � XSS

## 9. Encoded Class Distribution

In [21]:
print(df["Label"].value_counts().sort_index())

Label
0     1895232
1        1437
2      128014
3       10286
4      172846
5        5228
6        5385
7        5931
8          11
9          36
10       1956
11       3219
12       1470
13         21
14        652
Name: count, dtype: int64

## 10. Feature-Target Separation

In [22]:
X = df.drop("Label", axis=1)
y = df["Label"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2231724, 77)
y shape: (2231724,)

## 11. Train-Test Split

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (1785379, 77)
X_test : (446345, 77)
y_train: (1785379,)
y_test : (446345,)

## 12. Min-Max Scaling

In [24]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train scaled shape:", X_train_scaled.shape)
print("X_test scaled shape:", X_test_scaled.shape)

X_train scaled shape: (1785379, 77)
X_test scaled shape: (446345, 77)

In [25]:
# Save the scaled train/test data

pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
).to_parquet("X_train_scaled.parquet", index=False)

pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
).to_parquet("X_test_scaled.parquet", index=False)

# Save labels
y_train.to_frame("Label").to_parquet("y_train.parquet", index=False)
y_test.to_frame("Label").to_parquet("y_test.parquet", index=False)

## 13. Save the train/test data

In [26]:
X_train.to_parquet("X_train.parquet", index=False)
X_test.to_parquet("X_test.parquet", index=False)

y_train.to_frame("Label").to_parquet("y_train.parquet", index=False)
y_test.to_frame("Label").to_parquet("y_test.parquet", index=False)

In [27]:
pd.DataFrame({
    "encoded_label": range(len(le.classes_)),
    "class_name": le.classes_
}).to_csv("label_mapping.csv", index=False)